### ISSUE TITLE
--org  argument not implemented

### ISSUE THREAD

**Issue by rsinnet** [shippableSamples/sample-slack-notifications#11]
According to the docs, the `--org` argument is required. Looking through slack_notifier.py, this argument is not implemented. Was this something that was removed or yet to be implemented? Should the README be updated?

**Comment by rageshkrishna** [comment]
http://docs.shippable.com/platform/tutorial/workflow/using-shipctl/#notify is the "official" way to send customized notifications now. This script is no longer required.

**Comment by rsinnet** [comment]
:clap:
