### ISSUE TITLE
Any chance this will be a built-in feature in Shippable?

### ISSUE THREAD

**Issue by rockerhieu** [shippableSamples/sample-slack-notifications#6]
This plugin is cool. But it would be awesome if it is supported natively in Shippable.

**Comment by daniloisr** [comment]
:+1:

**Comment by rvrignaud** [comment]
+1

**Comment by malchmih** [comment]
+1

**Comment by pquentin** [comment]
:hamburger:

**Comment by Ivaylo-Bachvarov** [comment]
+1

**Comment by manishas** [comment]
@Ivaylo-Bachvarov http://blog.shippable.com/how-to-use-slack-integration-for-build-notifications

**Comment by pquentin** [comment]
@manishas Unfortunately we can't switch until https://github.com/Shippable/support/issues/1922 is fixed.

**Comment by a-murphy** [comment]
Slack messages from both [CI](http://docs.shippable.com/ci/slack-notifications/) and [Assembly Lines](http://docs.shippable.com/platform/tutorial/workflow/send-job-status-notifications/#sending-job-status-notifications) can be configured in `shippable.yml`.
